version: '3'
services:
    zk01:
        build: ./zookeeper
        image: zk
        restart: always
        ports:
            - "2181:2181"
            - "2888:2888"
            - "3888:3888"
        volumes:
            - "/opt/otter/data/zookeeper/data:/data/zookeeper"
            - "/opt/otter/data/zookeeper/log:/var/log/zookeeper"
        environment:
            - ZOO_MY_ID=1
            - ZOO_SERVERS=server.1=0.0.0.0:2888:3888 server.2=192.168.0.2:2888:3888 server.3=192.168.0.3:2888:3888

    zk02:
        build: ./zookeeper
        image: zk
        restart: always
        ports:
            - "2181:2181"
            - "2888:2888"
            - "3888:3888"
        volumes:
            - "/opt/otter/data/zookeeper/data:/data/zookeeper"
            - "/opt/otter/data/zookeeper/log:/var/log/zookeeper"
        environment:
            - ZOO_MY_ID=2
            - ZOO_SERVERS=server.1=192.168.0.1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=192.168.0.3:2888:3888

    zk03:
        build: ./zookeeper
        image: zk
        restart: always
        ports:
            - "2181:2181"
            - "2888:2888"
            - "3888:3888"
        volumes:
            - "/opt/otter/data/zookeeper/data:/data/zookeeper"
            - "/opt/otter/data/zookeeper/log:/var/log/zookeeper"
        environment:
            - ZOO_MY_ID=3
            - ZOO_SERVERS=server.1=192.168.0.1:2888:3888 server.2=192.168.0.2:2888:3888 server.3=0.0.0.0:2888:3888
